name: rickandmortyapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.10.0


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  flutter_bloc: ^8.1.6
  
  # HTTP & Networking
  http: ^1.2.2
  dio: ^5.7.0
  
  # Utilities
  hexcolor: ^3.0.1
  shared_preferences: ^2.3.3
  
  # Navigation
  go_router: ^14.6.2
  
  # Freezed & JSON Serialization
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  
  # Code Generation
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
  
  fonts:
    - family: cartoon
      fonts:
        - asset: assets/fonts/Balthazar-Regular.ttf
        
        
  

